server:
  port: 8081
  servlet:
    session:
      timeout: 30m
  shutdown: graceful

spring:
  application:
    name: dev-test
  profiles:
    active: local
    group:
      "local": "local"
      "dev": "dev"
  thymeleaf:
    prefix: classpath:templates/main/
    suffix: .html
    cache: false
    check-template-location: true
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: "local"
    import:
      - classpath:config/local/config.yml
      - classpath:config/local/datasource.yml